version: "3.9"
services:
  db:
    platform: linux/x86_64 # for M1 Mac
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_database_user
      MYSQL_PASSWORD: your_database_password

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8080:80"
    volumes:
      - ./vite-tailwind-theme:/var/www/html/wp-content/themes/vite-tailwind-theme
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: your_database_user
      WORDPRESS_DB_PASSWORD: your_database_password
      WORDPRESS_DB_NAME: your_database_name
volumes:
  db_data:
