name: Deploy Theme on push to develop

on:
  push:
    branches:
      - main

jobs:
  deploy-dev:
    name: Deploy-Dev
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      #   - name: 📂 Sync files
      #     uses: Dylan700/sftp-upload-action@v1.2.3
      #     with:
      #       server: ${{ secrets.FTP_SERVER_DEV }}
      #       username: ${{ secrets.FTP_USERNAME_DEV }}
      #       password: ${{ secrets.FTP_PASSWORD_DEV }}
      #       port: ${{ secrets.FTP_PORT_DEV }}
      #       uploads: |
      #         ./vite-tailwind-theme/ => .${{ secrets.SERVER_DIRECTORY_DEV }}

      - name: 📂 Sync files
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.FTP_USERNAME_DEV }}
          server: ${{ secrets.FTP_SERVER_DEV }}
          port: ${{ secrets.FTP_PORT_DEV }}
          local_path: "./vite-tailwind-theme/*"
          remote_path: ${{ secrets.SERVER_DIRECTORY_DEV }}
          sftp_only: true
          password: ${{ secrets.FTP_PASSWORD_DEV }}
