name: Deploy Theme on push to develop

on:
  push:
    branches:
      - main

jobs:
  deploy-dev:
    name: Deploy-Dev
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          cache-dependency-path: vite-tailwind-theme/pnpm-lock.yaml

      - name: Install dependencies
        working-directory: ./vite-tailwind-theme
        run: pnpm install

      - name: Build
        working-directory: ./vite-tailwind-theme
        run: |
          pnpm run tw:build

      - name: Delete node_modules
        run: rm -rf vite-tailwind-theme/node_modules

      - name: 📂 Sync files
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.FTP_USERNAME_DEV }}
          server: ${{ secrets.FTP_SERVER_DEV }}
          port: ${{ secrets.FTP_PORT_DEV }}
          local_path: "./vite-tailwind-theme/*"
          remote_path: ${{ secrets.SERVER_DIRECTORY_DEV }}
          sftp_only: true
          password: ${{ secrets.FTP_PASSWORD_DEV }}
